//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkbilYonetimiDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Akbiller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Akbiller()
        {
            this.Talimatlar = new HashSet<Talimatlar>();
        }
    
        public string AkbilNo { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public short AkbilTipi { get; set; }
        public decimal Bakiye { get; set; }
        public System.DateTime SonKullanimTarihi { get; set; }
        public int AkbilSahibiID { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Talimatlar> Talimatlar { get; set; }
    }
}
