//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkbilYonetimiDataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AKBİLYONETİMİDBEntities : DbContext
    {
        public AKBİLYONETİMİDBEntities()
            : base("name=AKBİLYONETİMİDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Akbiller> Akbiller { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilar { get; set; }
        public virtual DbSet<Talimatlar> Talimatlar { get; set; }
        public virtual DbSet<KullanicininTalimatlari> KullanicininTalimatlari { get; set; }
    
        public virtual int SP_BekleyenTalimatSayisi(Nullable<int> kullaniciId)
        {
            var kullaniciIdParameter = kullaniciId.HasValue ?
                new ObjectParameter("kullaniciId", kullaniciId) :
                new ObjectParameter("kullaniciId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_BekleyenTalimatSayisi", kullaniciIdParameter);
        }
    }
}
