//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkbilYonetimiDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Talimatlar
    {
        public int Id { get; set; }
        public System.DateTime OlustulmaTarihi { get; set; }
        public string AkbilID { get; set; }
        public decimal YuklenecekTutar { get; set; }
        public bool YuklendiMi { get; set; }
        public Nullable<System.DateTime> YuklendigiTarih { get; set; }
    
        public virtual Akbiller Akbiller { get; set; }
    }
}
